### ISSUE TITLE
对于验证器失败返回的问题

### ISSUE THREAD

**Issue by wantsingZhang** [Hansin1997/captcha#6]
求助大佬：图片验证码的验证注解@VerifyCode 是在控制器之前验证的，在其在验证失败该怎样让其返回指定的路径，比如失败后返回登录界面

**Comment by Hansin1997** [comment]
# 解决方案

验证失败的时候是会抛出异常的，可以写一个全局的异常拦截控制器，如下所示：

```java

@RestControllerAdvice
@CrossOrigin
public class ExceptionController {

    @ExceptionHandler(CaptchaException.class)
    public String onCaptchaException(CaptchaException e, HttpServletRequest request, HttpServletResponse response) {
        // 在这里进行统一验证码的异常处理，例如返回一个错误信息。也可以进行重定向。
        response.setStatus(HttpStatus.BAD_REQUEST.value());
        logger.debug(e.getMessage(), e);
        return e.getMessage();
    }

}
```

## 异常类说明

**VerifyFailException**：验证失败异常类。
**StoreCodeException**：验证码存储异常类。
**SendCodeException**：发送验证码异常类。
**GenerateCodeException**：生成验证码异常类。

**CaptchaException**：所有验证码异常类的父类。

根据你的描述，你应该取捕获 **VerifyFailException** 异常，并进行相关处理。

**Comment by wantsingZhang** [comment]
明白，十分感谢

**Comment by Hansin1997** [comment]
不用客气，感谢 star ⭐😀
