### ISSUE TITLE
VerifyCode注解只能放到Get方法的接口上吗，使用POST方法报错

### ISSUE THREAD

**Issue by Toxicist** [Hansin1997/captcha#8]

**Comment by Hansin1997** [comment]
注解可以放到 POST 方法的，麻烦把报错信息贴出来看看。🔍

**Comment by Toxicist** [comment]
![image](https://user-images.githubusercontent.com/75112052/127966083-32ffe7af-ef8f-44c2-9f26-1a1d9f540a5a.png)
![image](https://user-images.githubusercontent.com/75112052/127966117-86af4931-32cf-465e-af85-3534efa156f8.png)
![image](https://user-images.githubusercontent.com/75112052/127966168-5d03b531-902d-4a93-9cad-2d8ac05e1bb7.png)

**Comment by Toxicist** [comment]
localhost:8888/code/checkCode?code=xxxx可以验证

**Comment by Hansin1997** [comment]
POST 请求时如果验证码参数在请求体中，需要定义请求体的结构并在验证码字段加上 ```@CodeValue``` 字段。

详细说明请查看 #5
